"""empty message

Revision ID: 2b8a1ffd53a0
Revises: 7afc237cacc8
Create Date: 2024-03-21 15:32:36.138493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b8a1ffd53a0'
down_revision: Union[str, None] = '7afc237cacc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_token_blacklist_token', table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_index('ix_vapi_conversation_update_call_id', table_name='vapi_conversation_update')
    op.create_unique_constraint(None, 'vapi_conversation_update', ['call_id'])
    op.drop_constraint('vapi_conversation_update_call_id_fkey', 'vapi_conversation_update', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('vapi_conversation_update_call_id_fkey', 'vapi_conversation_update', 'vapi_end_of_call', ['call_id'], ['call_id'])
    op.drop_constraint(None, 'vapi_conversation_update', type_='unique')
    op.create_index('ix_vapi_conversation_update_call_id', 'vapi_conversation_update', ['call_id'], unique=False)
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='token_blacklist_pkey')
    )
    op.create_index('ix_token_blacklist_token', 'token_blacklist', ['token'], unique=True)
    # ### end Alembic commands ###
