"""empty message

Revision ID: 3440357f75c3
Revises: 2b8a1ffd53a0
Create Date: 2024-03-21 15:57:36.657852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3440357f75c3'
down_revision: Union[str, None] = '2b8a1ffd53a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_token_blacklist_token', table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_constraint('vapi_conversation_update_call_id_key', 'vapi_conversation_update', type_='unique')
    op.drop_constraint('vapi_conversation_update_id_key', 'vapi_conversation_update', type_='unique')
    op.drop_column('vapi_conversation_update', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vapi_conversation_update', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_unique_constraint('vapi_conversation_update_id_key', 'vapi_conversation_update', ['id'])
    op.create_unique_constraint('vapi_conversation_update_call_id_key', 'vapi_conversation_update', ['call_id'])
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='token_blacklist_pkey')
    )
    op.create_index('ix_token_blacklist_token', 'token_blacklist', ['token'], unique=True)
    # ### end Alembic commands ###
