"""empty message

Revision ID: 7afc237cacc8
Revises: 97083f39a3a6
Create Date: 2024-03-21 14:18:35.866454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7afc237cacc8'
down_revision: Union[str, None] = '97083f39a3a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_token_blacklist_token', table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.add_column('vapi_conversation_update', sa.Column('call_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_vapi_conversation_update_call_id'), 'vapi_conversation_update', ['call_id'], unique=False)
    op.create_foreign_key(None, 'vapi_conversation_update', 'vapi_end_of_call', ['call_id'], ['call_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vapi_conversation_update', type_='foreignkey')
    op.drop_index(op.f('ix_vapi_conversation_update_call_id'), table_name='vapi_conversation_update')
    op.drop_column('vapi_conversation_update', 'call_id')
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='token_blacklist_pkey')
    )
    op.create_index('ix_token_blacklist_token', 'token_blacklist', ['token'], unique=True)
    # ### end Alembic commands ###
