"""empty message

Revision ID: a0930f0347e0
Revises: 717ade5947a4
Create Date: 2024-03-21 09:42:56.284380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0930f0347e0'
down_revision: Union[str, None] = '717ade5947a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vapi_conversation_update',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('conversation', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'uuid'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_vapi_conversation_update_created_by_user_id'), 'vapi_conversation_update', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_vapi_conversation_update_is_deleted'), 'vapi_conversation_update', ['is_deleted'], unique=False)
    op.create_table('vapi_end_of_call',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('ended_reason', sa.String(length=50), nullable=False),
    sa.Column('call', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('phone_number', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.String(length=63206), nullable=False),
    sa.Column('transcript', sa.String(), nullable=False),
    sa.Column('messages', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('recording_url', sa.String(), nullable=True),
    sa.Column('stereo_recording_url', sa.String(), nullable=True),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'uuid'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_vapi_end_of_call_created_by_user_id'), 'vapi_end_of_call', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_vapi_end_of_call_is_deleted'), 'vapi_end_of_call', ['is_deleted'], unique=False)
    op.drop_index('ix_end_of_call_created_by_user_id', table_name='end_of_call')
    op.drop_index('ix_end_of_call_is_deleted', table_name='end_of_call')
    op.drop_table('end_of_call')
    op.drop_index('ix_token_blacklist_token', table_name='token_blacklist')
    op.drop_table('token_blacklist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='token_blacklist_pkey')
    )
    op.create_index('ix_token_blacklist_token', 'token_blacklist', ['token'], unique=True)
    op.create_table('end_of_call',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_by_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ended_reason', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('summary', sa.VARCHAR(length=63206), autoincrement=False, nullable=False),
    sa.Column('transcript', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('messages', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('recording_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('call', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('stereo_recording_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone_number', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], name='end_of_call_created_by_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'uuid', name='end_of_call_pkey'),
    sa.UniqueConstraint('id', name='end_of_call_id_key'),
    sa.UniqueConstraint('uuid', name='end_of_call_uuid_key')
    )
    op.create_index('ix_end_of_call_is_deleted', 'end_of_call', ['is_deleted'], unique=False)
    op.create_index('ix_end_of_call_created_by_user_id', 'end_of_call', ['created_by_user_id'], unique=False)
    op.drop_index(op.f('ix_vapi_end_of_call_is_deleted'), table_name='vapi_end_of_call')
    op.drop_index(op.f('ix_vapi_end_of_call_created_by_user_id'), table_name='vapi_end_of_call')
    op.drop_table('vapi_end_of_call')
    op.drop_index(op.f('ix_vapi_conversation_update_is_deleted'), table_name='vapi_conversation_update')
    op.drop_index(op.f('ix_vapi_conversation_update_created_by_user_id'), table_name='vapi_conversation_update')
    op.drop_table('vapi_conversation_update')
    # ### end Alembic commands ###
