"""empty message

Revision ID: a87673b5467b
Revises: 
Create Date: 2024-03-18 08:09:34.013717

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a87673b5467b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_token_blacklist_token", table_name="token_blacklist")
    op.drop_table("token_blacklist")
    # op.alter_column(
    #     "end_of_call",
    #     "messages",
    #     existing_type=sa.VARCHAR(length=63206),
    #     type_=postgresql.JSON(astext_type=sa.Text()),
    #     existing_nullable=False,
    # )
    op.execute(
        """
        ALTER TABLE end_of_call
        ALTER COLUMN messages TYPE JSON
        USING messages::json
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "end_of_call",
        "messages",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=sa.VARCHAR(length=63206),
        existing_nullable=False,
    )
    op.create_table(
        "token_blacklist",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("token", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="token_blacklist_pkey"),
    )
    op.create_index(
        "ix_token_blacklist_token", "token_blacklist", ["token"], unique=True
    )
    # ### end Alembic commands ###
