"""empty message

Revision ID: b0856a1db52b
Revises: 3440357f75c3
Create Date: 2024-03-21 16:10:52.312422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0856a1db52b'
down_revision: Union[str, None] = '3440357f75c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vapi_conversation_update',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('conversation', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_vapi_conversation_update_created_by_user_id'), 'vapi_conversation_update', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_vapi_conversation_update_is_deleted'), 'vapi_conversation_update', ['is_deleted'], unique=False)
    op.drop_index('ix_token_blacklist_token', table_name='token_blacklist')
    op.drop_table('token_blacklist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='token_blacklist_pkey')
    )
    op.create_index('ix_token_blacklist_token', 'token_blacklist', ['token'], unique=True)
    op.drop_index(op.f('ix_vapi_conversation_update_is_deleted'), table_name='vapi_conversation_update')
    op.drop_index(op.f('ix_vapi_conversation_update_created_by_user_id'), table_name='vapi_conversation_update')
    op.drop_table('vapi_conversation_update')
    # ### end Alembic commands ###
